#! /bin/sh

echo "1. Récupérez la liste des interfaces réseau de la machine sans afficher"
echo "   aucun détail pour ces interfaces. Vraiment juste la liste des noms."
echo "\nCOMMANDE: ifconfig -l"
ifconfig -l
echo "\nADD FORMAT: ifconfig -l | tr ' ' '\\\n' "
ifconfig -l | tr " " "\n"