#! /bin/sh

# COMMANDE 1: Identifiez et affichez les caractéristiques de l’interface Ethernet :
ifconfig -L en0
# COMMANDE 2:  Indiquez l’adresse de Broadcast
ifconfig -L en1 | grep "broadcast " | cut -d " " -f 6
# COMMANDE 3:  Indiquez toutes les adresses IP qui font partie du même sous-réseau