#! /bin/sh

echo "\n7. Interrogez un serveur DNS externe (ex :google 8.8.8.8) sur le nom de domaine slash16.org"
echo "\nCOMMANDE : nslookup slash16.org < externalservername >\n"
nslookup slash16.org 8.8.8.8
