#! /bin/sh

echo "\n8. Trouver chez quel hébergeur est le site de Slash16"
echo "\nCOMMANDE: 'dig NS slash16.org' -> affiche awsdns"
echo "COMMANDE: 'host slash16.org' -> affiche mail is handled by google "
echo "\nDEDUCTION : j'en deduis que c'est GOOGLE pour e-mail et AWS pour le site et le domain"
echo "\ndig NS slash16.org"
dig  NS slash16.org
echo "\nhost slash16.org "
host slash16.org 
