#! /bin/sh

echo "\n9. Trouver l’IP Publique de 42.fr / Find the external IP of 42.fr"
echo "\nCOMMANDE: dig +short 42.fr"
dig +short 42.fr
# 42.fr.			3600	IN	A	163.172.250.13
# 42.fr.			3600	IN	A	163.172.250.12

echo "\nCOMMANDE: dig +short 42.fr @resolver1.opendns.com "
dig +short 42.fr @resolver1.opendns.com 
# 163.172.250.12
# 163.172.250.13

echo "\nCOMMANDE: nslookup 42.fr"
nslookup 42.fr
# Address: 163.172.250.13
# Address: 163.172.250.12



