#! /bin/sh

echo "\n11. Trouvez grâce au résultat de la commande précédente le nom et l’IP du matériel"
echo " qui fait le lien entre vous (réseau local) et l’extérieur"
# 192.168.0.254 (192.168.0.254)  0.813 ms  1.080 ms  0.752 ms
# 78.194.89.254 (78.194.89.254)  2.432 ms  4.375 ms  1.113 ms
echo "\nDEDUCTION:  chez moi 192.168.0.254, à 42 nat-1.42.fr (10.60.1.11)"
echo "              nat-1 c'est le materiel qui fait le lien entre réseau local et l’extérieur"