#! /bin/sh

# 12. Trouvez l’IP qui vous a été assignée par le serveur dhcp
# COMMANDE :







# Git : Figure out the server type
# Deduction: 
echo Server is of DHCP type
# DHCP, Dynamic Host Configuration Protocol, is a client/server protocol 
# that automatically provides an Internet Protocol (IP) host with its IP address 
# and other related configuration information such as the subnet mask and default gateway
