#! /bin/sh

echo "\n12. Trouvez l’IP qui vous a été assignée par le serveur DHCP"
echo "\nCOMMANDE : ifconfig -L en1 | grep 'inet '' | cut -d ' ' -f 2"
ifconfig -L en1 | grep "inet " | cut -d " " -f 2
echo "SORTIE : 10.0.1.4"




# Old 12: Figure out the server type
# Deduction: 
# echo Server is of DHCP type
# DHCP, Dynamic Host Configuration Protocol, is a client/server protocol 
# that automatically provides an Internet Protocol (IP) host with its IP address 
# and other related configuration information such as the subnet mask and default gateway
