#! /bin/sh

echo "\n14. Quel est le fichier contenant les entrées locales DNS ?"
echo "\nDEDUCTION: /etc/hosts"
cat  /etc/hosts

# cat /etc/hosts
# 127.0.0.1	localhost
# 255.255.255.255	broadcasthost
# ::1             localhost
# fe80::1%lo0	localhost
