#! /bin/sh

echo "\n15. Faites pointer intra.42.fr sur l’adresse suivante 46.19.122.85"
 
echo "\nDEDUCTION: "
echo "il faut ajouter une configuration locale dans le fichier /etc/hosts pour associer"
echo "cad ajouter l'adresse ip  46.19.122.85 au contenu du fichier /etc/hosts et lui attribuer le nom 'intra.42.fr' "
sudo echo '46.19.122.85  intra.42.fr' >> /etc/hosts
cat /etc/hosts