#! /bin/sh

# 5. Donnez une commande qui détermine l’état du service SSH / Name the command that determines the state of the SSH service.
# COMMANDE :
service ssh status

# systemctl status ssh.service  // aussi sur debian
