#! /bin/sh
echo "5. Donnez une commande qui détermine l’état du service SSH."
echo "5. COMMANDE : service ssh status"
service ssh status  # marche pas sur virtual box
systemctl status ssh.service # marche pas sur virtual box
/etc/init.d/ssh status # marche pas sur virtual box