#! /bin/sh

# 11. Quelle commande permet d’afficher l’espace disponible et utilisé sur le système d’une manière humainement compréhensible ?
# COMMANDE : 
df -h /
# Name the command that displays the available space left on the system?
df /
