#! /bin/sh

echo "14. Lancez en background la commande tail -f /var/log/syslog"
echo "14. COMMANDE: la meme commande suivie de & . "
echo " Encore mieux c'est de la redirigier vers un fichier '> filename &' "
tail -f /var/log/syslog > afile &
