#!/bin/bash
#echo "1. Réalisez un script qui affiche seulement le login, le UID et le Path de chaques entrée du fichier /etc/passwd"
echo "1. Write a script which displays only the login, UID and Path of each entry of the /etc/passwd file"

#old
sudo cat /etc/passwd | awk -F  ":" '{print $1 "   " $3 "   " $6}' | column -t
# column -t to arrange 

# new
echo  "LOGIN              UID    PATH"
sudo cat /etc/passwd | cut -d ':' -f1-1,3-3,7-7 | sed 's/:/ /g' | column -t