#!/bin/sh
# 3. Jamais 2 sans 3. Réalise un script de ton choix.
# A script which monitors the modifications made to the /etc/hosts file and
# sends an e-mail to root when file is modified. 
# Create a scheduled task to run this script everyday at 0h42


# add this line to /etc/cron.d/hosts_check
echo "42 0 * * *   root    sh /root/hosts_check.sh" > /etc/cron.d/hosts_check
service cron restart

cat > /root/hosts_check.sh << EOF
#!/bin/sh
diff /etc/hosts /etc/hosts.backup
if [ $? -ne 0 ] ; then
	diff /etc/hosts /etc/hosts.backup | mail -s "The file hosts was modified" root@localhost.com
	cp /etc/hosts /etc/hosts.backup
fi
EOF
